-- Gerado por scripts/gen-seed.mjs — NÃO editar à mão. Rode depois do schema.sql.
-- Idempotente: limpa e recria os dados de catálogo.
begin;
delete from public.produtos;
delete from public.categorias;

insert into public.categorias (slug, titulo, descricao, imagem, badge, badge_mod, destaque, ordem) values ('selas', 'Selas', 'Selas artesanais em couro legítimo, feitas à mão para durar anos.', 'assets/images/sela.webp', 'Mais pedido', '', false, 1);
insert into public.categorias (slug, titulo, descricao, imagem, badge, badge_mod, destaque, ordem) values ('arreios', 'Arreios', 'Arreios completos e acessórios equestres em couro selecionado.', 'assets/images/arreio.webp', null, '', false, 2);
insert into public.categorias (slug, titulo, descricao, imagem, badge, badge_mod, destaque, ordem) values ('cintos', 'Cintos', 'Cintos em couro legítimo com bordados e acabamentos personalizados.', 'assets/images/cinto.webp', 'Sob medida', 'dark', false, 3);
insert into public.categorias (slug, titulo, descricao, imagem, badge, badge_mod, destaque, ordem) values ('bolsas', 'Bolsas & Acessórios', 'Bolsas, carteiras e porta-documentos com acabamento artesanal.', 'assets/images/bolsa.webp', null, '', false, 4);
insert into public.categorias (slug, titulo, descricao, imagem, badge, badge_mod, destaque, ordem) values ('consertos', 'Consertos & Restauração', 'Costura, reforço, restauração e hidratação de peças em couro.', 'assets/images/conserto.webp', null, '', false, 5);
insert into public.categorias (slug, titulo, descricao, imagem, badge, badge_mod, destaque, ordem) values ('sobmedida', 'Sob Medida', 'Peças personalizadas do seu jeito, com seu nome e suas medidas.', 'assets/images/personalizado.webp', 'Especial', 'gold', true, 6);

insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'selas'), 'Sela de Vaqueiro', 'Sela artesanal estilo vaqueiro, em couro curtido de alta resistência. Trabalhada à mão para encaixe perfeito e durabilidade excepcional.', ARRAY['Couro curtido de alta resistência', 'Acabamento manual caprichado', 'Ajuste personalizado disponível']::text[], 'Mais pedido', '', 'assets/images/sela.webp', 1);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'selas'), 'Sela Inglesa', 'Sela no estilo inglês, leve e de encaixe preciso. Ideal para hipismo e equitação clássica com couro de primeira linha.', ARRAY['Couro macio e resistente', 'Design clássico e elegante', 'Pode ser feita sob medida']::text[], null, '', 'assets/images/sela.webp', 2);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'selas'), 'Sela Personalizada', 'Sela 100% personalizada conforme suas especificações: medidas, acabamentos, gravações e cor do couro do seu jeito.', ARRAY['Projeto junto com o cliente', 'Gravação e bordado opcional', 'Medidas exatas do cavaleiro']::text[], 'Sob medida', 'gold', 'assets/images/personalizado.webp', 3);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'arreios'), 'Arreio Completo', 'Conjunto completo de arreio em couro selecionado, com todas as peças necessárias para equipar seu animal com segurança e durabilidade.', ARRAY['Couro curtido e selecionado', 'Peças costuradas a mão', 'Ferragens de qualidade']::text[], null, '', 'assets/images/arreio.webp', 1);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'arreios'), 'Cabeçada', 'Cabeçadas em couro legítimo para cavalos e outros animais. Resistentes, confortáveis e com acabamento artesanal.', ARRAY['Vários tamanhos disponíveis', 'Ajuste regulável', 'Gravação do nome do animal']::text[], null, '', 'assets/images/arreio.webp', 2);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'arreios'), 'Rédeas e Acessórios', 'Rédeas, peitorais, grupeiras e demais acessórios equestres feitos com o mesmo cuidado e qualidade de toda a nossa linha.', ARRAY['Diversos modelos', 'Material resistente', 'Pode complementar seu arreio']::text[], null, '', 'assets/images/arreio.webp', 3);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'cintos'), 'Cinto Liso', 'Cinto em couro legítimo com acabamento liso e elegante. Disponível em diversas espessuras e larguras, com fivela a escolher.', ARRAY['Couro legítimo nacional', 'Fivelas em diversas opções', 'Sob medida sem custo extra']::text[], 'Sob medida', 'dark', 'assets/images/cinto.webp', 1);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'cintos'), 'Cinto com Bordado', 'Cinto artesanal com bordado e trabalhos manuais exclusivos. Cada peça é única — um verdadeiro objeto de artesanato.', ARRAY['Bordados feitos à mão', 'Motivos personalizados', 'Presente sofisticado']::text[], 'Artesanal', '', 'assets/images/cinto.webp', 2);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'cintos'), 'Cinto de Montaria', 'Cinturão robusto de montaria, com couro mais espesso e fivela reforçada. Feito para aguentar o trabalho pesado no campo.', ARRAY['Couro espesso e resistente', 'Fivela reforçada', 'Ideal para o trabalho no campo']::text[], null, '', 'assets/images/cinto.webp', 3);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'bolsas'), 'Bolsa de Couro', 'Bolsas femininas e masculinas em couro legítimo, com costura manual e acabamento caprichado. Durabilidade de décadas.', ARRAY['Couro legítimo de qualidade', 'Costura manual reforçada', 'Vários modelos e tamanhos']::text[], null, '', 'assets/images/bolsa.webp', 1);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'bolsas'), 'Carteira & Porta-documentos', 'Carteiras, porta-documentos e pequenos acessórios em couro fino. Práticos, elegantes e com longa vida útil.', ARRAY['Couro fino e macio', 'Compartimentos bem organizados', 'Gravação do nome possível']::text[], null, '', 'assets/images/bolsa.webp', 2);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'bolsas'), 'Acessórios de Montaria', 'Alforjes, porta-garrafas, saca-coisas e outros acessórios de montaria feitos para durar muito mais que os industrializados.', ARRAY['Feitos para uso intenso', 'Material selecionado', 'Sob medida disponível']::text[], null, '', 'assets/images/bolsa.webp', 3);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'consertos'), 'Conserto de Selas e Arreios', 'Sua sela ou arreio com costura solta, couro ressecado ou ferragem quebrada? A Márcia resolve com o mesmo capricho de uma peça nova.', ARRAY['Costura e reforço de peças', 'Troca de fivelas e ferragens', 'Avaliação sem compromisso']::text[], null, '', 'assets/images/conserto.webp', 1);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'consertos'), 'Restauração de Peças Antigas', 'Tem aquela peça com história que merecia uma segunda vida? Restauração de peças antigas em couro, com respeito pela originalidade.', ARRAY['Restauração cuidadosa', 'Hidratação e limpeza profunda', 'Peças com valor sentimental']::text[], 'Especial', 'gold', 'assets/images/conserto.webp', 2);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'consertos'), 'Conserto de Cintos e Bolsas', 'Cinto desgastado, bolsa com alça solta ou fivela partida? Trazemos de volta ao estado original sem a dor de jogar fora uma boa peça.', ARRAY['Troca de alças e fechos', 'Reforço de pontos fracos', 'Hidratação e acabamento']::text[], null, '', 'assets/images/conserto.webp', 3);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'sobmedida'), 'Cinto para Coluna', 'Cinto ortopédico em couro legítimo para suporte lombar. Acabamento artesanal com costura reforçada, interior acolchoado e fivela metálica — feito sob medida para o seu conforto.', ARRAY['Couro legítimo com costura reforçada', 'Interior acolchoado para conforto', 'Medidas personalizadas']::text[], 'Sob medida', 'gold', 'assets/images/cinto-coluna.webp', 1);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'sobmedida'), 'Peça Personalizada', 'Tem uma ideia na cabeça? A Márcia faz. Descreva o que você quer — o couro, o tamanho, os detalhes — e receba uma peça única.', ARRAY['Projeto junto com o cliente', 'Gravação e bordado personalizado', 'Presente com significado']::text[], 'Especial', 'gold', 'assets/images/personalizado.webp', 2);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'sobmedida'), 'Presente Personalizado', 'Um presente em couro com o nome da pessoa, uma data especial ou um brasão de família. Algo que vai durar e ser lembrado.', ARRAY['Gravação de nomes e datas', 'Embalagem especial disponível', 'Prazo combinado com antecedência']::text[], 'Presente', '', 'assets/images/personalizado.webp', 3);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'sobmedida'), 'Encomenda Especial', 'Peças fora do padrão — tamanhos especiais, combinações incomuns, projetos únicos. Se é de couro, a Márcia sente, analisa e faz.', ARRAY['Sem limitação de modelo', 'Consulta gratuita por WhatsApp', 'Orçamento sem compromisso']::text[], null, '', 'assets/images/personalizado.webp', 4);

commit;
