-- Gerado por scripts/gen-seed.mjs - NAO editar a mao. Rode depois do schema.sql.
-- Idempotente: limpa e recria os dados de catalogo.
begin;
delete from public.produtos;
delete from public.categorias;

insert into public.categorias (slug, titulo, descricao, imagem, badge, badge_mod, destaque, ordem) values ('selas', 'Selas', E'Selas artesanais em couro leg\u00edtimo, feitas \u00e0 m\u00e3o para durar anos.', 'assets/images/sela.webp', 'Mais pedido', '', false, 1);
insert into public.categorias (slug, titulo, descricao, imagem, badge, badge_mod, destaque, ordem) values ('arreios', 'Arreios', E'Arreios completos e acess\u00f3rios equestres em couro selecionado.', 'assets/images/arreio.webp', null, '', false, 2);
insert into public.categorias (slug, titulo, descricao, imagem, badge, badge_mod, destaque, ordem) values ('cintos', 'Cintos', E'Cintos em couro leg\u00edtimo com bordados e acabamentos personalizados.', 'assets/images/cinto.webp', 'Sob medida', 'dark', false, 3);
insert into public.categorias (slug, titulo, descricao, imagem, badge, badge_mod, destaque, ordem) values ('bolsas', E'Bolsas & Acess\u00f3rios', 'Bolsas, carteiras e porta-documentos com acabamento artesanal.', 'assets/images/bolsa.webp', null, '', false, 4);
insert into public.categorias (slug, titulo, descricao, imagem, badge, badge_mod, destaque, ordem) values ('consertos', E'Consertos & Restaura\u00e7\u00e3o', E'Costura, refor\u00e7o, restaura\u00e7\u00e3o e hidrata\u00e7\u00e3o de pe\u00e7as em couro.', 'assets/images/conserto.webp', null, '', false, 5);
insert into public.categorias (slug, titulo, descricao, imagem, badge, badge_mod, destaque, ordem) values ('sobmedida', 'Sob Medida', E'Pe\u00e7as personalizadas do seu jeito, com seu nome e suas medidas.', 'assets/images/personalizado.webp', 'Especial', 'gold', true, 6);

insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'selas'), 'Sela de Vaqueiro', E'Sela artesanal estilo vaqueiro, em couro curtido de alta resist\u00eancia. Trabalhada \u00e0 m\u00e3o para encaixe perfeito e durabilidade excepcional.', ARRAY[E'Couro curtido de alta resist\u00eancia', 'Acabamento manual caprichado', E'Ajuste personalizado dispon\u00edvel']::text[], 'Mais pedido', '', 'assets/images/sela.webp', 1);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'selas'), 'Sela Inglesa', E'Sela no estilo ingl\u00eas, leve e de encaixe preciso. Ideal para hipismo e equita\u00e7\u00e3o cl\u00e1ssica com couro de primeira linha.', ARRAY['Couro macio e resistente', E'Design cl\u00e1ssico e elegante', 'Pode ser feita sob medida']::text[], null, '', 'assets/images/sela.webp', 2);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'selas'), 'Sela Personalizada', E'Sela 100% personalizada conforme suas especifica\u00e7\u00f5es: medidas, acabamentos, grava\u00e7\u00f5es e cor do couro do seu jeito.', ARRAY['Projeto junto com o cliente', E'Grava\u00e7\u00e3o e bordado opcional', 'Medidas exatas do cavaleiro']::text[], 'Sob medida', 'gold', 'assets/images/personalizado.webp', 3);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'arreios'), 'Arreio Completo', E'Conjunto completo de arreio em couro selecionado, com todas as pe\u00e7as necess\u00e1rias para equipar seu animal com seguran\u00e7a e durabilidade.', ARRAY['Couro curtido e selecionado', E'Pe\u00e7as costuradas a m\u00e3o', 'Ferragens de qualidade']::text[], null, '', 'assets/images/arreio.webp', 1);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'arreios'), E'Cabe\u00e7ada', E'Cabe\u00e7adas em couro leg\u00edtimo para cavalos e outros animais. Resistentes, confort\u00e1veis e com acabamento artesanal.', ARRAY[E'V\u00e1rios tamanhos dispon\u00edveis', E'Ajuste regul\u00e1vel', E'Grava\u00e7\u00e3o do nome do animal']::text[], null, '', 'assets/images/arreio.webp', 2);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'arreios'), E'R\u00e9deas e Acess\u00f3rios', E'R\u00e9deas, peitorais, grupeiras e demais acess\u00f3rios equestres feitos com o mesmo cuidado e qualidade de toda a nossa linha.', ARRAY['Diversos modelos', 'Material resistente', 'Pode complementar seu arreio']::text[], null, '', 'assets/images/arreio.webp', 3);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'cintos'), 'Cinto Liso', E'Cinto em couro leg\u00edtimo com acabamento liso e elegante. Dispon\u00edvel em diversas espessuras e larguras, com fivela a escolher.', ARRAY[E'Couro leg\u00edtimo nacional', E'Fivelas em diversas op\u00e7\u00f5es', 'Sob medida sem custo extra']::text[], 'Sob medida', 'dark', 'assets/images/cinto.webp', 1);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'cintos'), 'Cinto com Bordado', E'Cinto artesanal com bordado e trabalhos manuais exclusivos. Cada pe\u00e7a \u00e9 \u00fanica \u2014 um verdadeiro objeto de artesanato.', ARRAY[E'Bordados feitos \u00e0 m\u00e3o', 'Motivos personalizados', 'Presente sofisticado']::text[], 'Artesanal', '', 'assets/images/cinto.webp', 2);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'cintos'), 'Cinto de Montaria', E'Cintur\u00e3o robusto de montaria, com couro mais espesso e fivela refor\u00e7ada. Feito para aguentar o trabalho pesado no campo.', ARRAY['Couro espesso e resistente', E'Fivela refor\u00e7ada', 'Ideal para o trabalho no campo']::text[], null, '', 'assets/images/cinto.webp', 3);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'bolsas'), 'Bolsa de Couro', E'Bolsas femininas e masculinas em couro leg\u00edtimo, com costura manual e acabamento caprichado. Durabilidade de d\u00e9cadas.', ARRAY[E'Couro leg\u00edtimo de qualidade', E'Costura manual refor\u00e7ada', E'V\u00e1rios modelos e tamanhos']::text[], null, '', 'assets/images/bolsa.webp', 1);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'bolsas'), 'Carteira & Porta-documentos', E'Carteiras, porta-documentos e pequenos acess\u00f3rios em couro fino. Pr\u00e1ticos, elegantes e com longa vida \u00fatil.', ARRAY['Couro fino e macio', 'Compartimentos bem organizados', E'Grava\u00e7\u00e3o do nome poss\u00edvel']::text[], null, '', 'assets/images/bolsa.webp', 2);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'bolsas'), E'Acess\u00f3rios de Montaria', E'Alforjes, porta-garrafas, saca-coisas e outros acess\u00f3rios de montaria feitos para durar muito mais que os industrializados.', ARRAY['Feitos para uso intenso', 'Material selecionado', E'Sob medida dispon\u00edvel']::text[], null, '', 'assets/images/bolsa.webp', 3);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'consertos'), 'Conserto de Selas e Arreios', E'Sua sela ou arreio com costura solta, couro ressecado ou ferragem quebrada? A M\u00e1rcia resolve com o mesmo capricho de uma pe\u00e7a nova.', ARRAY[E'Costura e refor\u00e7o de pe\u00e7as', 'Troca de fivelas e ferragens', E'Avalia\u00e7\u00e3o sem compromisso']::text[], null, '', 'assets/images/conserto.webp', 1);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'consertos'), E'Restaura\u00e7\u00e3o de Pe\u00e7as Antigas', E'Tem aquela pe\u00e7a com hist\u00f3ria que merecia uma segunda vida? Restaura\u00e7\u00e3o de pe\u00e7as antigas em couro, com respeito pela originalidade.', ARRAY[E'Restaura\u00e7\u00e3o cuidadosa', E'Hidrata\u00e7\u00e3o e limpeza profunda', E'Pe\u00e7as com valor sentimental']::text[], 'Especial', 'gold', 'assets/images/conserto.webp', 2);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'consertos'), 'Conserto de Cintos e Bolsas', E'Cinto desgastado, bolsa com al\u00e7a solta ou fivela partida? Trazemos de volta ao estado original sem a dor de jogar fora uma boa pe\u00e7a.', ARRAY[E'Troca de al\u00e7as e fechos', E'Refor\u00e7o de pontos fracos', E'Hidrata\u00e7\u00e3o e acabamento']::text[], null, '', 'assets/images/conserto.webp', 3);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'sobmedida'), 'Cinto para Coluna', E'Cinto ortop\u00e9dico em couro leg\u00edtimo para suporte lombar. Acabamento artesanal com costura refor\u00e7ada, interior acolchoado e fivela met\u00e1lica \u2014 feito sob medida para o seu conforto.', ARRAY[E'Couro leg\u00edtimo com costura refor\u00e7ada', 'Interior acolchoado para conforto', 'Medidas personalizadas']::text[], 'Sob medida', 'gold', 'assets/images/cinto-coluna.webp', 1);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'sobmedida'), E'Pe\u00e7a Personalizada', E'Tem uma ideia na cabe\u00e7a? A M\u00e1rcia faz. Descreva o que voc\u00ea quer \u2014 o couro, o tamanho, os detalhes \u2014 e receba uma pe\u00e7a \u00fanica.', ARRAY['Projeto junto com o cliente', E'Grava\u00e7\u00e3o e bordado personalizado', 'Presente com significado']::text[], 'Especial', 'gold', 'assets/images/personalizado.webp', 2);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'sobmedida'), 'Presente Personalizado', E'Um presente em couro com o nome da pessoa, uma data especial ou um bras\u00e3o de fam\u00edlia. Algo que vai durar e ser lembrado.', ARRAY[E'Grava\u00e7\u00e3o de nomes e datas', E'Embalagem especial dispon\u00edvel', E'Prazo combinado com anteced\u00eancia']::text[], 'Presente', '', 'assets/images/personalizado.webp', 3);
insert into public.produtos (categoria_id, nome, descricao, detalhes, badge, badge_mod, imagem, ordem) values ((select id from public.categorias where slug = 'sobmedida'), 'Encomenda Especial', E'Pe\u00e7as fora do padr\u00e3o \u2014 tamanhos especiais, combina\u00e7\u00f5es incomuns, projetos \u00fanicos. Se \u00e9 de couro, a M\u00e1rcia sente, analisa e faz.', ARRAY[E'Sem limita\u00e7\u00e3o de modelo', 'Consulta gratuita por WhatsApp', E'Or\u00e7amento sem compromisso']::text[], null, '', 'assets/images/personalizado.webp', 4);

commit;
